version: '3.7'
services:
  srv:
    image: captaingeech/cube2srv
    ports:
      - "28785:28785/tcp"
      - "28785:28785/udp"
      - "28786:28786/tcp"
      - "28786:28786/udp"
    volumes:
      - "./server-init.cfg:/.sauerbraten/server-init.cfg"
